version: '3.8'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
  postgres_data: 
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro 
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.rootfs=/rootfs' 
      - '--path.sysfs=/host/sys' 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' 
    ports: 
      - 9100:9100 
    networks: 
      - monitoring 

  prometheus: 
    image: prom/prometheus:latest
    user: ${MY_UID}:${MY_GID}
    container_name: prometheus 
    restart: unless-stopped
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml' 
      - '--storage.tsdb.path=/prometheus' 
      - '--web.console.libraries=/etc/prometheus/console_libraries' 
      - '--web.console.templates=/etc/prometheus/consoles' 
      - '--web.enable-lifecycle' 
    ports: 
      - 9090:9090 
    networks: 
      - monitoring 
  grafana: 
    image: grafana/grafana:latest 
    user: "501" 
    container_name: grafana 
    ports: 
      - 3000:3000 
    restart: unless-stopped 
    # volumes:
    #   - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources 
    #   - ./grafana:/var/lib/grafana 
    networks: 
      - monitoring 

  postgres:
    image: postgres:latest
    container_name: postgres
    user: ${MY_UID}:${MY_GID}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: example 
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    networks:
      - monitoring
  
  # postgres-exporter:
  #   container_name: postgresql-exporter
  #   image: prometheuscommunity/postgres-exporter
  #   ports:
  #     - 9187:9817
  #   environment:
  #     DATA_SOURCE_NAME : "postgresql://example:example@postgres:5432/example?sslmodel=disable"
  #   depends_on:
  #     - postgres
  #     - prometheus

  # pgadmin:
  #   image: dpage/pgadmin4:6
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@email.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_PORT: 5050
  #   ports:
  #     - "5050:5050"