global: 
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs: 
  - job_name: "prometheus" 
    scrape_interval: 15s 
    static_configs: 
    - targets: ["host.docker.internal:9090"]

  - job_name: "node" 
    static_configs: 
    - targets: ["node-exporter:9100"]

  - job_name: "hvhost01" 
    scrape_interval: 5s 
    static_configs:
    - targets: ["10.1.149.191:9182"]

  - job_name: 'docker'
    static_configs:
      - targets: ["localhost:9323"]
  
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ["postgres-exporter:9187"]